version: '3.8'
services:
  redis:
    image: redis:7.2.9
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      TZ: Asia/Seoul
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD:-}
    restart: always # 컨테이너 비정상 종료 또는 호스트 재부팅 시 자동 재시작

  pinback:
    image: ${DOCKER_USERNAME}/pinback:latest
    container_name: pinback-server-container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - pinback.env
    volumes:
      - /home/ubuntu/pinback/firebase-service-account.json:/app/firebase-service-account.json:ro
    environment:
      TZ: Asia/Seoul
      FCM_JSON: /app/firebase-service-account.json
    restart: always

volumes:
  redis_data: